### ISSUE TITLE
Safecast publishing?

### ISSUE THREAD

**Issue by matschaffer** [openradiation/openradiation#7]
Very cool project!

If you're interested it'd be great to have your data in the safecast data set. Our next-gen database could be a great fit.

https://github.com/Safecast/ingest/blob/master/script/example_data.sh is an example on publishing, and https://github.com/Safecast/safecastapi/wiki/Data-Sets#data-published-via-ingestsafecastorg has details on where the data ends up.

I see you've got some `safecast_id` going on which looks sort of like a bgeigie device id.

We're planning on updating ingest to use a urn instead of a numeric ID shortly.

Maybe it would make sense to have you POST your uploads as `openradiation:(ID)`?

Would be happy to discuss any technical details any time. :)

**Comment by ghisd** [comment]
Hi 

Sorry for the late reply and thank you for warning me about the change from an id to an URN.

We have had discussions with Azby Brown (from Safecast) about each other's projects.

I think our projects are complementary. Our objective is that Safecast device owners could use our plateform.  We already provide a web page to upload safecast data (see https://submit.openradiation.net/en/upload or https://www.openradiation.org/en/data, I think it's why you saw safecast id) and we're working now to make our application compatible with the BLE safecast device.

I'm not sure it make sense to send all our data in the Safecast database. Our database is entirely published with an opendata licence too but the licences are not the same (we choose ODBL) so it could be confusing to automatically send openradiation data in safecast database. 

But if safecast device owners ask us to be able to send data in the safecast database with our application, your API could be useful

**Comment by matschaffer** [comment]
Ahh, yes maybe best to keep storage separate given the licenses. I'll close this and open something around having a "paved road" for utilizing both data sets.
