### ISSUE TITLE
cannot find the logo & typo

### ISSUE THREAD

**Issue by adelkheniche** [openradiation/openradiation#8]
For an event at @fablab sorbonne university we need the logo + name in vectoriel format. 

we want to make  a physical version of it  with the laser cutter.
i can't find the file on the website.  

we would love to have it.

**Comment by ghisd** [comment]
You can find logo here : https://github.com/openradiation/openradiation-mobile/blob/master/www/img/temp/Objet%20dynamique%20vectoriel.pdf
Although the project is entirely opensource, OpenRadiation is a trademark : please do not use the logo for an other usage
